{application,sentry,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"The Official Elixir client for Sentry"},
              {modules,['Elixir.Mix.Tasks.Sentry.SendTestEvent',
                        'Elixir.Sentry','Elixir.Sentry.Client',
                        'Elixir.Sentry.Config','Elixir.Sentry.Context',
                        'Elixir.Sentry.CrashError',
                        'Elixir.Sentry.DefaultEventFilter',
                        'Elixir.Sentry.Event','Elixir.Sentry.EventFilter',
                        'Elixir.Sentry.HTTPClient',
                        'Elixir.Sentry.HackneyClient',
                        'Elixir.Sentry.LoggerBackend',
                        'Elixir.Sentry.PlugCapture',
                        'Elixir.Sentry.PlugContext','Elixir.Sentry.Sources',
                        'Elixir.Sentry.Util']},
              {registered,[]},
              {vsn,"8.0.6"},
              {mod,{'Elixir.Sentry',[]}}]}.
