{application,clickhouse_ecto,
             [{applications,[kernel,stdlib,elixir,logger,ecto_sql,
                             clickhousex]},
              {description,"Ecto adapter for ClickHouse database (uses clickhousex driver)"},
              {modules,['Elixir.ClickhouseEcto',
                        'Elixir.ClickhouseEcto.Connection',
                        'Elixir.ClickhouseEcto.Helpers',
                        'Elixir.ClickhouseEcto.Migration',
                        'Elixir.ClickhouseEcto.Query',
                        'Elixir.ClickhouseEcto.QueryString',
                        'Elixir.ClickhouseEcto.Storage',
                        'Elixir.ClickhouseEcto.Structure',
                        'Elixir.ClickhouseEcto.Type']},
              {registered,[]},
              {vsn,"0.2.8"}]}.
